// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLw1fVV0jybUeHsHZfRPsMS6v1LUWLnYQ',
    appId: '1:959984253746:web:c9a4b8535dca7bcec6352b',
    messagingSenderId: '959984253746',
    projectId: 'resturantpager',
    authDomain: 'resturantpager.firebaseapp.com',
    databaseURL: 'https://resturantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resturantpager.appspot.com',
    measurementId: 'G-Z9C9D9TRXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0GQF-wQsjib5soErL3a98RxI3VAcCpPA',
    appId: '1:959984253746:android:44071b3f9766f479c6352b',
    messagingSenderId: '959984253746',
    projectId: 'resturantpager',
    databaseURL: 'https://resturantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resturantpager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3_6igcDyXPkKqCS0RYOLpXCjS9YStASE',
    appId: '1:959984253746:ios:de1b23663ed4b280c6352b',
    messagingSenderId: '959984253746',
    projectId: 'resturantpager',
    databaseURL: 'https://resturantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resturantpager.appspot.com',
    iosClientId: '959984253746-qqdlun4flp8r3t3jrti7fo2ftt7dme11.apps.googleusercontent.com',
    iosBundleId: 'com.example.restuarantPagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3_6igcDyXPkKqCS0RYOLpXCjS9YStASE',
    appId: '1:959984253746:ios:de1b23663ed4b280c6352b',
    messagingSenderId: '959984253746',
    projectId: 'resturantpager',
    databaseURL: 'https://resturantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resturantpager.appspot.com',
    iosClientId: '959984253746-qqdlun4flp8r3t3jrti7fo2ftt7dme11.apps.googleusercontent.com',
    iosBundleId: 'com.example.restuarantPagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLw1fVV0jybUeHsHZfRPsMS6v1LUWLnYQ',
    appId: '1:959984253746:web:f1a7bf70663fd25dc6352b',
    messagingSenderId: '959984253746',
    projectId: 'resturantpager',
    authDomain: 'resturantpager.firebaseapp.com',
    databaseURL: 'https://resturantpager-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resturantpager.appspot.com',
    measurementId: 'G-ZTBXS9WJEL',
  );
}
